### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by vidartf** [eugeniy/pytest-tornado#41]
@eugeniy As you mentioned in https://github.com/eugeniy/pytest-tornado/pull/30, you moved on from python development, and wanted to transition the maintenance of the project to the pytest-dev org. How is this proceeding? In the meantime, would you mind adding a few others as maintainers? I'd be happy to volunteer some time for reviewing PRs and doing releases.

**Comment by Jamim** [comment]
Hey @eugeniy,
We miss you! :cry:

**Comment by Jamim** [comment]
@scopatz yes, and I'm one of those who interested in.

**Comment by betatim** [comment]
I've switched to https://github.com/pytest-dev/pytest-asyncio which works well. I think contributing there instead of creating a fork would be a good idea.

**Comment by vidartf** [comment]
I already have a fork I've been updating and releasing: https://github.com/vidartf/pytest-tornado  (pypi: https://pypi.org/project/pytest-tornado5/ ). I've only been adding critical fixes for working with newer versions of pytest and tornado. That is a bit of a quick-fix, so if someone has a proposal for a better way to maintain a fork, I'm all ears.

**Comment by vidartf** [comment]
@betatim What would a tornado fixture with `pytest-asyncio` look like? That sounds like a good example to have in the readme (or linked to a gist?). If it does all the things that are needed, that might be a better solution.

**Comment by betatim** [comment]
Most of my knowledge comes from looking at JupyterHub's setup and the oauthenticator package for JupyterHub.

**Comment by scopatz** [comment]
Thanks for putting up the fork @vidartf - that seems like the right thing to do

**Comment by okin** [comment]
I have very loose test dependencies in order to be able to easily pick up the latest version of test plugins in use. Unfortunately with pytest 4 out and commonly in use I find pytest-tornado breaking for me in a lot of places and would love to see some progress on getting this project back to being maintained!
@vidartf If help maintaining is wanted feel free to message me.

Would it be an option to fork the project to the pytest-dev org and then use [pep 541](https://www.python.org/dev/peps/pep-0541/) to gain ownership of the project on PyPI?
This unfortunately seems like the more hostile route but I can't see that we will have any progress here in the future.

**Comment by eugeniy** [comment]
Gave @vidartf owner access to pypi and collaborator to this repo.

**Comment by vidartf** [comment]
I merged some existing PRs into master, and have now opened #43 to update master further. Any feedback from those in this thread on that PR would be very welcome!
